config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :lists
  resources :plannings
  resources :products
  resources :recipes
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/planning.rb
class Planning < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :plannings
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
      @chatroom = Chatroom.find(params[:id])
      @message = Message.new
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show

  end

  def new
    @list = List.new
  end

  def edit

  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        @chatroom = Chatroom.find(params[:chatroom_id])
        @message = Message.new(message_params)
        @message.chatroom = @chatroom
        @message.user = current_user
        if @message.save
          ChatroomChannel.broadcast_to(
            @chatroom,
            render_to_string(partial: "message", locals: {message: @message})
          )
          head :ok
        end
      end

      private

      def message_params
        params.require(:message).permit(:content)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
     @user = current_user
  end

  def dashboard
     @user = current_user
  end

  def profile
     @user = current_user
  end

  def settings
     @user = current_user
  end
end

app/controllers/plannings_controller.rb
class PlanningsController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all

    @markers = @recipes.geocoded.map do |recipe|
      {
        lat: recipe.latitude,
        lng: recipe.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { recipe: recipe }),
        image_url: helpers.asset_url('yami.jpeg')
      }
    end
  end

  def show
  end

  def new
    @recipe = Recipe.new
    @recipes = Recipe.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe, notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @recipes.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Recipe was successfully destroyed."
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, :pic_url, :longitude, :latitude, :user_id, :address, photos: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/_navbar.html.erb
<%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "yami.jpeg" %>
<% end %>

<% if user_signed_in? %>
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" data-bs-toggle="dropdown"><%= current_user.nickname %></a>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </li>
<% else %>

app/views/chatrooms/show.html.erb
<%= simple_form_for [@chatroom, @message],
  html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
%>
  <%= f.input :content,
    label: false,
    placeholder: "Message ##{@chatroom.name}",
    wrapper_html: {class: "flex-grow-1"}
  %>
  <%= f.submit "Send", class: "btn btn-primary mb-3" %>
<% end %>

<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1>#<%= @chatroom.name %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <title>FoodamentalMobile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
     <%= render "shared/navbar" unless @disable_nav %>
    <%= render "shared/flashes" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
     <div class="global-wrapper">
    </div>
     <div class="nm-wrapper">
      <%= render "shared/navbarmobile" unless @disable_nav  %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="create-profile-form">
  <%= simple_form_for(@list, html: {"data-turbo": false}) do |f| %>

    <%= f.input :name, label: "New list" %>
    <div class="btn-sc">
      <div class="submit-btn">
        <%= f.submit %>
      </div>
      <div>
        <%= link_to "CANCEL", lists_path %>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/_list.html.erb
<div>
  <p>
    <strong>New list:</strong>
    <%= list.name %>
  </p>
</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<div class="saving-list-wrapper">
  <div class="saving-text">
     <p>Start Saving Food</p>
  </div>
  <div class="list-icon">
     <img src="https://cdn-icons-png.flaticon.com/512/1069/1069138.png" alt="list-img" class="list-img" />
     <p>My first list</p>
     <p>Go to the magic button and hold product for each day</p>
  </div>
  <div>
     <%= link_to "CREATE", new_list_path, class: "create-btn" %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<%= render @list %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @list, method: :delete, data: { confirm: 'Are you sure?'}%>
</div>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.nickname %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="page-wrapper">
  <div class="page-container">
    <%= render "shared/usersigning" %>
  </div>
  <div class="search-wrapper">
    <input type="text" name="search" placeholder="Search..." class="searching" />
    <i class="fa-solid fa-magnifying-glass"></i>
  </div>
  <div class="banner-wrapper">
      <div id="banner" style="background-image: url('https://images.unsplash.com/photo-1502741384106-56538427cde9?ixlib=rb-1.2.1&       ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2669&q=80');">
         Hola Pic
      </div>
  </div>
  <div class="options-wrapper">
     <div class="opt">
         <img src="https://cdn-icons-png.flaticon.com/512/1625/1625048.png" alt="pic" class="img-opt" />
     </div>
     <div class="opt">
          <img src="https://cdn-icons-png.flaticon.com/512/2098/2098402.png" alt="pic" class="img-opt"/>
     </div>
     <div class="opt">
        <img src="https://cdn-icons-png.flaticon.com/512/3565/3565418.png" alt="pic" class="img-opt"/>
     </div>
  </div>
</div>

<div class="card-container">
  <div>
    <h4>World's Recipes</h4>
  </div>
  <div class="recipes-card-wrapper">
    <div class="card">
      <img src="https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?ixlib=rb-1.2.ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&  auto=format&fit=crop&w=1287&q=80" alt="recipe" />
    </div>
    <p>lorem ipsum tonnu alitum
     Nosfritum</p>
  </div>
  <div class="recipes-card-wrapper">
    <div class="card">
      <img src="https://images.unsplash.com/photo-1506368249639-73a05d6f6488?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&  auto=format&fit=crop&w=1287&q=80" alt="recipe" />
    </div>
    <p>lorem ipsum tonnu alitum
     Nosfritum</p>
  </div>
  <div class="recipes-card-wrapper">
    <div class="card">
      <img src="https://images.unsplash.com/photo-1604634077373-a279cadc62c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&  auto=format&fit=crop&w=2670&q=80" alt="recipe" />
    </div>
    <p>lorem ipsum tonnu alitum
     Nosfritum</p>
  </div>
  <div class="recipes-card-wrapper">
    <div class="card">
      <img src="https://images.unsplash.com/photo-1562923690-e274ba919781?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&  auto=format&fit=crop&w=1376&q=80" alt="recipe" />
    </div>
    <p>lorem ipsum tonnu alitum
     Nosfritum</p>
  </div>
</div>

app/views/plannings/index.html.erb
<h1>Plannings#index</h1>
<p>Find me in app/views/plannings/index.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/recipes/_form.html.erb
<div class = "form">
  <%= simple_form_for(@recipe) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
     <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <div class="form-actions">
        <%= f.button :submit, 'ADD' %>
      </div>
  <% end %>
</div>

app/views/recipes/_info_window.html.erb
<h2><%= recipe.title %></h2>
<p><%= recipe.address %></p>

app/views/recipes/index.html.erb
<h1>Recipes of the world</h1>
<div class="button">
    <%= link_to "Give us a new recipe", new_recipe_path %>
</div>

<% @recipes.each do |recipe| %>
   <%= link_to recipe.title,  recipe_path(recipe) %>
<% end %>

<div class="map-wrapper">
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/recipes/new.html.erb
<h1 class = "header">Show us your creative Recipe</h1>
  <%= render "form", Recipe: @recipe %>

app/views/recipes/show.html.erb
<h1>Recipes of the world</h1>
<div class="button">
    <%= link_to "Give us a new recipe", new_recipe_path %>
</div>

<% @recipe.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<%= button_to "Delete recipe", @recipe, link_to: recipes_path(@recipe), method: :delete, data: { confirm: "Are you sure?" } %>


<%#= cl_image_tag @recipe.photo.key, height: 300, width: 400, crop: :fill %>

<div class="map-wrapper">
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">

    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon btn btn-dark"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-light" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">

      <div class="offcanvas-header">
        <h2 class="fooda-text" id="offcanvasDarkNavbarLabel">Foodamental</h2>
        <button type="button" class="btn-close btn-close-black" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="menu-wrapper">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
           <% if user_signed_in? %>
          <!--<li class="nav-item dropdown">
            <%#= image_tag "https://cdn-icons-png.flaticon.com/512/3033/3033143.png" , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>-->
          <li class="nav-item active">
            <div class="couple-wrapper">
              <i class="fa-solid fa-house-user fa-2x" style="color: #7a7a7a"></i>
              <%= link_to "Home",  root_path, class: "couple-text"%>
            </div>
          </li>
          <li class="nav-item active">
            <div class="couple-wrapper">
              <i class="fa-solid fa-book fa-2x" style="color: #7a7a7a"></i>
              <%= link_to "My experiences", root_path, class: "couple-text" %>
            </div>
          </li>
          <li class="nav-item active">
            <div class="couple-wrapper">
              <i class="fa-solid fa-clipboard-list fa-2x" style="color: #7a7a7a"></i>
              <%= link_to "My listing", lists_path, class: "couple-text" %>
            </div>
          </li>
          <li class="nav-item active">
            <div class="couple-wrapper">
              <i class="fa-solid fa-right-from-bracket fa-2x" style="color: #7a7a7a"></i>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "couple-text" %>
            </div>
          </li>
           <% else %>
             <li class="nav-item active">
               <%= link_to "Login", new_user_session_path, class: "nav-link" %>
             </li>
           <% end %>
          </ul>
          <div class="roll-menu-img">
            <img src="https://img.freepik.com/vector-gratis/salva-concepto-planeta-personas-que-cuidan-tierra_23-2148522570.jpg?w=1800&t=st=1662325050~exp=1662325650~hmac=a0dc8aee7610c36f511e5357767bcdf669b1b0efc8cea9604e7b9a6bcfa50786" alt="Logo">
          </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbarmobile.html.erb
<div class="icon-wrapper">
    <%= link_to root_path do %>
     <i class="fa-solid fa-house-user fa-2x" style="color: #fff"></i>
   <% end %>

     <i class="fa-solid fa-comments fa-2x" style="color: #fff"></i>

   <i class="fa-solid fa-circle-plus fa-2x" style="color: #fff"></i>
   <i class="fa-sharp fa-solid fa-location-dot fa-2x" style="color: #fff"></i>
   <i class="fa-solid fa-compass fa-2x" style="color: #fff"></i>
</div>

app/views/shared/_usersigning.html.erb
<div class="user-wrapper">
   <% if user_signed_in? %>
         <%= image_tag "https://cdn-icons-png.flaticon.com/512/3033/3033143.png" , class: "avatar dropdown-toggle", id: "navbarDropdown",   data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% @user.email %>
             <p>Enjoy and start to saving food</p>
        <% else %>
        <div class="nav-item">
          <%= image_tag "https://cdn-icons-png.flaticon.com/512/3033/3033143.png" , class: "avatar dropdown-toggle", id: "navbarDropdown",   data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%= link_to "Please login", new_user_session_path, class: "nav-link" %>
        </div>
    <% end %>
</div>